meson: Add missing build dependencies on glu
With current versions of meson, multiple build errors occur due to
gl_wrap.h pulling in GL/glu.h, which is included by various sources,
e.g.:

    In file included from ../src/egl/opengl/xeglgears.c:45:
    ../src/util/gl_wrap.h:13:12: fatal error: GL/glu.h: No such file or directory
       13 | #  include <GL/glu.h>
          |            ^~~~~~~~~~