meson: disable eglfbdev on non-Linux (requires Mesa < 10.6, anyway)
src/egl/opengles1/eglfbdev.c:43:10: fatal error: 'linux/kd.h' file not found
 #include <linux/kd.h>
          ^~~~~~~~~~~~

Reviewed-by: Hoe Hao Cheng <haochengho12907@gmail.com>