es2_info: turn it into a proper .c file
It was a symlink. Occasionally, this confuses git (or something else),
causing this error message to pop up:

../src/egl/opengles2/es2_info.c:1:1: error: expected identifier or `(` before `.` token

Reviewed-by: Erik Faye-Lund <erik.faye-lund@collabora.com>